### ISSUE TITLE
Failed to build via docker compose

### ISSUE THREAD

**Issue by asrob** [percona/pmm-server#13]
Hi,

I would like to build pmm-server via docker compose but it failed.
I got the following error:

> Step 8/21 : RUN curl -s -LO https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.2-1481203731_amd64.deb && 	dpkg -i grafana_4.0.2-1481203731_amd64.deb && 	git clone https://github.com/percona/grafana-dashboards.git && 	/opt/grafana-postinstall.sh && 	cp /opt/VERSION /var/lib/grafana/ && 	rm -rf grafana_4.0.2-1481203731_amd64.deb grafana-dashboards/.git
>  ---> Running in ada5a606b63d
> Selecting previously unselected package grafana.
> (Reading database ... 15280 files and directories currently installed.)
> Preparing to unpack grafana_4.0.2-1481203731_amd64.deb ...
> Unpacking grafana (4.0.2-1481203731) ...
> Setting up grafana (4.0.2-1481203731) ...
> Adding system user `grafana' (UID 103) ...
> Adding new user `grafana' (UID 103) with group `grafana' ...
> Not creating home directory `/usr/share/grafana'.
> ### NOT starting grafana-server by default on bootup, please execute
>  sudo update-rc.d grafana-server defaults 95 10
> ### In order to start grafana-server, execute
>  sudo service grafana-server start
> Processing triggers for ureadahead (0.100.0-16) ...
> Cloning into 'grafana-dashboards'...
>  * Starting Grafana Server
>    ...done.
> Traceback (most recent call last):
>   File "/opt/import-dashboards.py", line 118, in <module>
>     main()
>   File "/opt/import-dashboards.py", line 44, in main
>     "VALUES (1, 'PMM Dashboard Import', '%s', 'Admin', datetime('now'), datetime('now'))" % (db_key,))
> sqlite3.OperationalError: database is locked
> ERROR: Service 'pmm-data' failed to build: The command '/bin/sh -c curl -s -LO https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.2-1481203731_amd64.deb && 	dpkg -i grafana_4.0.2-1481203731_amd64.deb && 	git clone https://github.com/percona/grafana-dashboards.git && 	/opt/grafana-postinstall.sh && 	cp /opt/VERSION /var/lib/grafana/ && 	rm -rf grafana_4.0.2-1481203731_amd64.deb grafana-dashboards/.git' returned a non-zero code: 1

**Comment by dbpercona** [comment]
Hi asrob,  

Thank you for the report.   We have been able to reproduce the problem.   I have moved this to our Jira system here: https://jira.percona.com/browse/PMM-536

This is where all of the bug reports for PMM are stored.   We will be deactivating the issues system here soon.

**Comment by asrob** [comment]
Hi @dbpercona,

thank you very much. I've already registered.
